array_width = 80
attr_fn_like_width = 80
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
chain_width = 80
combine_control_expr = true
comment_width = 80
fn_args_layout = "Compressed"
fn_call_width = 80
fn_params_layout = "Compressed"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = false
doc_comment_code_block_width = 100
format_generated_files = true
format_macro_matchers = false
format_macro_bodies = true
format_strings = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_arm_blocks = true
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
merge_derives = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
struct_lit_single_line = true
struct_lit_width = 30
tab_spaces = 2
trailing_comma = "Vertical"
type_punctuation_density = "Compressed"
where_single_line = true
wrap_comments = true
